version: '3'
services:
  mysql-locacao:
    image: mysql:5.7.22
    container_name: locacao
    hostname: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: locacao
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
    volumes:
      - ./sql/data:/var/lib/mysql
    #  - ./scripts/sql/setup_database.sql:/docker-entrypoint-initdb.d/setup_database.sql
    command: ["mysqld", "--log-bin=mysql-bin", "--server-id=1"]

