server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost/locacao?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    mvc:
      view:
        prefix: classpath:/templates/
        sufix: .jsp
  jpa:
    hibernate:
      ddl-auto: create
